In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
file_name = 'Covid-19.csv'
folder_path = r'..\Datos-COVID19\output\producto1'
file_path = os.path.join(folder_path, file_name)

In [48]:
df_cmn = pd.read_csv(file_path)
df_cmn

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
0,Arica y Parinacota,15,Arica,15101,247552.0,6.0,6.0,12.0,41.0,63.0,87.0,115.0,124.0,134.0,166.0,67.1
1,Arica y Parinacota,15,Camarones,15102,1233.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Arica y Parinacota,15,General Lagos,15202,810.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Arica y Parinacota,15,Putre,15201,2515.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Tarapacá,1,Alto Hospicio,1107,129999.0,0.0,0.0,0.0,5.0,6.0,10.0,14.0,15.0,16.0,27.0,20.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,Magallanes,12,Punta Arenas,12101,141984.0,29.0,87.0,143.0,203.0,207.0,299.0,387.0,416.0,470.0,516.0,363.4
342,Magallanes,12,Rio Verde,12103,211.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
343,Magallanes,12,San Gregorio,12104,681.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
344,Magallanes,12,Timaukel,12303,282.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
345,Magallanes,12,Torres del Paine,12402,1021.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [83]:
dict_area = {'Pedro Aguirre Cerda':12.0,
             'Cerrillos':21.0,
             'Quinta Normal':10.0,
             'Nunoa':16.9,
             'Las Condes':99.0,
             'Providencia':14.34,
             'Quilicura':58.0,
             'Iquique':20.9,
             'Antofagasta':15.0,
             'Alto Hospicio':20.0,
             'Arica':11.0,
             'El Bosque':14.1,
             'San Bernardo':39.5,
             'Lo Barnechea':38.0,
             'Independencia':7.0,
             'Santiago':23.2,
             'Vitacura':22.4}

In [84]:
quar_name = 'quarantine.csv'
folder_path = r'..\covid-19'
quar_path = os.path.join(folder_path, quar_name)

In [85]:
df_qrt = pd.read_csv(quar_path)
df_qrt['Fecha'] = pd.to_datetime(df_qrt['Fecha'])
df_qrt.sort_values(by='Fecha', inplace=True)
df_qrt

                 Comuna      Fecha Estado Nivel
9          Lo Barnechea 2020-03-24     in  full
3         Independencia 2020-03-24     in  full
4              Santiago 2020-03-24     in  full
5           Providencia 2020-03-24     in  full
6                 Nunoa 2020-03-24     in  full
7            Las Condes 2020-03-24     in  full
8              Vitacura 2020-03-24     in  full
10        Independencia 2020-03-31    out  full
17          Puente Alto 2020-04-07     in  half
15                Ñuñoa 2020-04-07    out  half
11         Lo Barnechea 2020-04-07    out  full
12             Vitacura 2020-04-07    out  full
13          Providencia 2020-04-07    out  full
14             Santiago 2020-04-07    out  half
16           Las Condes 2020-04-14    out  full
19         San Bernardo 2020-04-14     in  full
18            El Bosque 2020-04-14     in  full
2         Independencia 2020-04-21     in  half
1         Quinta Normal 2020-04-21     in  full
0   Pedro Aguirre Cerda 2020-04-21     in  full

In [86]:
in_cnd = (df_qrt['Estado'] == 'in') & (df_qrt['Nivel'] == 'full')
#dt_cnd =  df_qrt['Fecha'] > pd.to_datetime('2020-04-12')
df_qrt_in = df_qrt[in_cnd]

gdf_in = df_qrt_in.groupby('Fecha')

cmn_date = []
for grp, df in gdf_in:
    for ind, row in df.iterrows():
        cmn_date.append({'Comuna':row['Comuna'],
                         'Fecha' :row['Fecha'].strftime("%Y-%m-%d")})
cmn_date

[{'Comuna': 'Lo Barnechea', 'Fecha': '2020-03-24'},
 {'Comuna': 'Independencia', 'Fecha': '2020-03-24'},
 {'Comuna': 'Santiago', 'Fecha': '2020-03-24'},
 {'Comuna': 'Providencia', 'Fecha': '2020-03-24'},
 {'Comuna': 'Nunoa', 'Fecha': '2020-03-24'},
 {'Comuna': 'Las Condes', 'Fecha': '2020-03-24'},
 {'Comuna': 'Vitacura', 'Fecha': '2020-03-24'},
 {'Comuna': 'San Bernardo', 'Fecha': '2020-04-14'},
 {'Comuna': 'El Bosque', 'Fecha': '2020-04-14'},
 {'Comuna': 'Quinta Normal', 'Fecha': '2020-04-21'},
 {'Comuna': 'Pedro Aguirre Cerda', 'Fecha': '2020-04-21'}]

In [87]:
lst_cmn = []
for dct in cmn_date:
    lst_cmn.append(dct['Comuna'])

lst_df = []
ncmn = len(lst_cmn)

for ind in range(ncmn):
    lst_df.append(df_cmn[df_cmn.Comuna == lst_cmn[ind]]) 

for ind in range(ncmn):
    display(lst_df[ind])

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
103,Metropolitana,13,Lo Barnechea,13115,124076.0,68.0,78.0,85.0,97.0,105.0,110.0,116.0,125.0,144.0,157.0,126.5

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
94,Metropolitana,13,Independencia,13108,142065.0,15.0,17.0,22.0,26.0,31.0,37.0,52.0,60.0,80.0,115.0,80.9

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
130,Metropolitana,13,Santiago,13101,503147.0,127.0,156.0,173.0,234.0,271.0,321.0,375.0,404.0,463.0,500.0,99.4

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
117,Metropolitana,13,Providencia,13123,157749.0,82.0,87.0,94.0,104.0,115.0,129.0,136.0,147.0,164.0,180.0,114.1

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
110,Metropolitana,13,Nunoa,13120,250192.0,67.0,84.0,93.0,107.0,118.0,155.0,171.0,188.0,217.0,240.0,95.9

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
102,Metropolitana,13,Las Condes,13114,330759.0,181.0,208.0,224.0,258.0,266.0,281.0,296.0,306.0,320.0,326.0,98.6

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
133,Metropolitana,13,Vitacura,13132,96774.0,83.0,90.0,100.0,114.0,114.0,119.0,127.0,128.0,130.0,132.0,136.4

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
124,Metropolitana,13,San Bernardo,13401,334836.0,32.0,41.0,53.0,74.0,79.0,117.0,140.0,156.0,198.0,237.0,70.8

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
90,Metropolitana,13,El Bosque,13105,172000.0,18.0,28.0,35.0,37.0,46.0,64.0,83.0,93.0,107.0,127.0,73.8

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
121,Metropolitana,13,Quinta Normal,13126,136368.0,21.0,25.0,35.0,41.0,57.0,69.0,84.0,105.0,125.0,149.0,109.3

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,2020-04-10,2020-04-13,2020-04-15,2020-04-17,2020-04-20,Tasa
113,Metropolitana,13,Pedro Aguirre Cerda,13121,107803.0,7.0,13.0,13.0,16.0,19.0,36.0,54.0,70.0,78.0,89.0,82.6

In [88]:
def bld_df(df, area):
    index = []
    cases = []
    df_out = pd.DataFrame()
    index = list(df.columns[5:-1].values)
    idx = df.index[0]
    for date in index:
        num = df.loc[idx][date]
        cases.append(float(num)) 
    index.insert(0,'2020-3-28')
    cases.insert(0,float(0))
    index = [pd.to_datetime(ind) for ind in index]
    df_out = pd.DataFrame(cases, index=index, columns=['cum_cases'])
    df_out['date']                = df_out.index.values    
    df_out['cum_cases_per_100th'] = 1e5 * df_out['cum_cases'] / float(df.Poblacion)
    df_out['new_cases']           = df_out['cum_cases'].diff(periods=1)
    df_out['new_cases3']          = df_out['cum_cases'].diff(periods=3)
    df_out['new_cases5']          = df_out['cum_cases'].diff(periods=5)
    df_out['new_cases7']          = df_out['cum_cases'].diff(periods=7)
    df_out['shift_cum_cases']     = df_out['cum_cases'].shift(1, axis=0)
    df_out['increment']           = 100.0 * df_out['new_cases'] / df_out['cum_cases']
    df_out['increment3']          = 100.0 * df_out['new_cases3'] / df_out['cum_cases']
    df_out['increment5']          = 100.0 * df_out['new_cases5'] / df_out['cum_cases']
    df_out['increment7']          = 100.0 * df_out['new_cases7'] / df_out['cum_cases']
    df_out['new_cases_per_100th'] = 1e5 * df_out['new_cases'] / float(df.Poblacion)
    df_out['new_cases3_per_100th']= 1e5 * df_out['new_cases3'] / float(df.Poblacion)
    df_out['new_cases5_per_100th']= 1e5 * df_out['new_cases5'] / float(df.Poblacion)
    df_out['new_cases7_per_100th']= 1e5 * df_out['new_cases7'] / float(df.Poblacion)
    df_out['new_cas_per_100th_area'] = 1e5 * df_out['new_cases'] / float(df.Poblacion) / area
    df_out['new_cas3_per_100th_area']= 1e5 * df_out['new_cases3'] / float(df.Poblacion) / area
    df_out['new_cas5_per_100th_area']= 1e5 * df_out['new_cases5'] / float(df.Poblacion) / area
    df_out['new_cas7_per_100th_area']= 1e5 * df_out['new_cases7'] / float(df.Poblacion) / area
    
    
    return df_out

def itp_df(df):
    df_itp = df.resample('D').mean()
    df_itp = df_itp.interpolate()
    
    return df_itp

In [89]:
lst_ts = []
lst_ts_tmp = []

for ind in range(ncmn):
    area = dict_area[lst_cmn[ind]]
    lst_ts_tmp.append(bld_df(lst_df[ind], area))

for ind in range(ncmn):
    lst_ts.append(itp_df(lst_ts_tmp[ind]))

for ind in range(ncmn):
    print(lst_cmn[ind])
    display(lst_ts[ind])

Lo Barnechea

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,34.000000,27.402560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,68.000000,54.805119,68.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,54.805119,NaN,NaN,NaN,1.442240,NaN,NaN,NaN
2020-03-31,73.000000,58.834908,39.000000,NaN,NaN,NaN,34.000000,56.410256,NaN,NaN,NaN,31.432348,NaN,NaN,NaN,0.827167,NaN,NaN,NaN
2020-04-01,78.000000,62.864696,10.000000,NaN,NaN,NaN,68.000000,12.820513,NaN,NaN,NaN,8.059576,NaN,NaN,NaN,0.212094,NaN,NaN,NaN
2020-04-02,81.500000,65.685548,8.500000,NaN,NaN,NaN,73.000000,10.527903,NaN,NaN,NaN,6.850640,NaN,NaN,NaN,0.180280,NaN,NaN,NaN
2020-04-03,85.000000,68.506399,7.000000,85.000000,NaN,NaN,78.000000,8.235294,100.000000,NaN,NaN,5.641703,68.506399,NaN,NaN,0.148466,1.802800,NaN,NaN
2020-04-04,89.000000,71.730230,8.666667,66.333333,NaN,NaN,80.333333,9.613907,76.632302,NaN,NaN,6.984966,53.461857,NaN,NaN,0.183815,1.406891,NaN,NaN
2020-04-05,93.000000,74.954060,10.333333,47.666667,NaN,NaN,82.666667,10.992521,53.264605,NaN,NaN,8.328229,38.417314,NaN,NaN,0.219164,1.010982,NaN,NaN
2020-04-06,97.000000,78.177891,12.000000,29.000000,NaN,NaN,85.000000,12.371134,29.896907,NaN,NaN,9.671492,23.372772,NaN,NaN,0.254513,0.615073,NaN,NaN
2020-04-07,101.000000,81.401722,10.000000,28.000000,NaN,NaN,91.000000,9.995091,27.805596,NaN,NaN,8.059576,22.566814,NaN,NaN,0.212094,0.593864,NaN,NaN
2020-04-08,105.000000,84.625552,8.000000,27.000000,105.000000,NaN,97.000000,7.619048,25.714286,100.000000,NaN,6.447661,21.760856,84.625552,NaN,0.169675,0.572654,2.226988,NaN
2020-04-09,107.500000,86.640446,6.500000,26.000000,73.500000,NaN,101.000000,6.082251,24.220779,69.090909,NaN,5.238725,20.954899,59.237886,NaN,0.137861,0.551445,1.558892,NaN
2020-04-10,110.000000,88.655340,5.000000,25.000000,42.000000,NaN,105.000000,4.545455,22.727273,38.181818,NaN,4.029788,20.148941,33.850221,NaN,0.106047,0.530235,0.890795,NaN
2020-04-11,112.000000,90.267256,5.333333,23.000000,40.666667,NaN,106.666667,4.754441,20.611285,36.374086,NaN,4.298441,18.537026,32.775611,NaN,0.113117,0.487816,0.862516,NaN
2020-04-12,114.000000,91.879171,5.666667,21.000000,39.333333,NaN,108.333333,4.963427,18.495298,34.566353,NaN,4.567093,16.925110,31.701000,NaN,0.120187,0.445398,0.834237,NaN
2020-04-13,116.000000,93.491086,6.000000,19.000000,38.000000,116.0,110.000000,5.172414,16.379310,32.758621,100.000000,4.835746,15.313195,30.626390,93.491086,0.127256,0.402979,0.805958,2.460292
2020-04-14,120.500000,97.117895,7.500000,19.500000,39.000000,86.5,113.000000,6.186207,16.189655,32.379310,72.800000,6.044682,15.716174,31.432348,69.715336,0.159071,0.413584,0.827167,1.834614
2020-04-15,125.000000,100.744705,9.000000,20.000000,40.000000,57.0,116.000000,7.200000,16.000000,32.000000,45.600000,7.253619,16.119153,32.238306,45.939585,0.190885,0.424188,0.848376,1.208936
2020-04-16,134.500000,108.401302,14.000000,27.000000,43.500000,61.5,120.500000,10.197222,19.805556,32.319444,45.716667,11.283407,21.760856,35.059157,49.566395,0.296932,0.572654,0.922609,1.304379
2020-04-17,144.000000,116.057900,19.000000,34.000000,47.000000,66.0,125.000000,13.194444,23.611111,32.638889,45.833333,15.313195,27.402560,37.880009,53.193204,0.402979,0.721120,0.996842,1.399821
2020-04-18,148.333333,119.550383,17.000000,36.333333,48.666667,68.0,131.333333,11.556381,24.445624,32.799599,45.842180,13.701280,29.283128,39.223272,54.805119,0.360560,0.770609,1.032191,1.442240
2020-04-19,152.666667,123.042866,15.000000,38.666667,50.333333,70.0,137.666667,9.918318,25.280137,32.960309,45.851026,12.089365,31.163695,40.566534,56.417035,0.318141,0.820097,1.067540,1.484659
2020-04-20,157.000000,126.535349,13.000000,41.000000,52.000000,72.0,144.000000,8.280255,26.114650,33.121019,45.859873,10.477449,33.044263,41.909797,58.028950,0.275722,0.869586,1.102889,1.527078

Independencia

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,7.500000,5.279274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,15.000000,10.558547,15.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,10.558547,NaN,NaN,NaN,1.508364,NaN,NaN,NaN
2020-03-31,16.000000,11.262450,8.500000,NaN,NaN,NaN,7.500000,55.882353,NaN,NaN,NaN,5.983177,NaN,NaN,NaN,0.854740,NaN,NaN,NaN
2020-04-01,17.000000,11.966353,2.000000,NaN,NaN,NaN,15.000000,11.764706,NaN,NaN,NaN,1.407806,NaN,NaN,NaN,0.201115,NaN,NaN,NaN
2020-04-02,19.500000,13.726111,3.500000,NaN,NaN,NaN,16.000000,17.245989,NaN,NaN,NaN,2.463661,NaN,NaN,NaN,0.351952,NaN,NaN,NaN
2020-04-03,22.000000,15.485869,5.000000,22.000000,NaN,NaN,17.000000,22.727273,100.000000,NaN,NaN,3.519516,15.485869,NaN,NaN,0.502788,2.212267,NaN,NaN
2020-04-04,23.333333,16.424407,4.666667,18.333333,NaN,NaN,18.666667,20.279720,80.769231,NaN,NaN,3.284881,12.904891,NaN,NaN,0.469269,1.843556,NaN,NaN
2020-04-05,24.666667,17.362944,4.333333,14.666667,NaN,NaN,20.333333,17.832168,61.538462,NaN,NaN,3.050247,10.323913,NaN,NaN,0.435750,1.474845,NaN,NaN
2020-04-06,26.000000,18.301482,4.000000,11.000000,NaN,NaN,22.000000,15.384615,42.307692,NaN,NaN,2.815613,7.742935,NaN,NaN,0.402230,1.106134,NaN,NaN
2020-04-07,28.500000,20.061240,4.500000,12.500000,NaN,NaN,24.000000,15.756824,43.734491,NaN,NaN,3.167564,8.798789,NaN,NaN,0.452509,1.256970,NaN,NaN
2020-04-08,31.000000,21.820997,5.000000,14.000000,31.000000,NaN,26.000000,16.129032,45.161290,100.000000,NaN,3.519516,9.854644,21.820997,NaN,0.502788,1.407806,3.117285,NaN
2020-04-09,34.000000,23.932707,5.500000,14.500000,26.500000,NaN,28.500000,16.172624,42.850915,79.729730,NaN,3.871467,10.206596,18.653433,NaN,0.553067,1.458085,2.664776,NaN
2020-04-10,37.000000,26.044416,6.000000,15.000000,22.000000,NaN,31.000000,16.216216,40.540541,59.459459,NaN,4.223419,10.558547,15.485869,NaN,0.603346,1.508364,2.212267,NaN
2020-04-11,42.000000,29.563932,9.000000,18.666667,26.333333,NaN,33.000000,20.426195,43.693694,62.075537,NaN,6.335128,13.139525,18.536116,NaN,0.905018,1.877075,2.648017,NaN
2020-04-12,47.000000,33.083448,12.000000,22.333333,30.666667,NaN,35.000000,24.636175,46.846847,64.691615,NaN,8.446838,15.720504,21.586363,NaN,1.206691,2.245786,3.083766,NaN
2020-04-13,52.000000,36.602963,15.000000,26.000000,35.000000,52.0,37.000000,28.846154,50.000000,67.307692,100.000000,10.558547,18.301482,24.636610,36.602963,1.508364,2.614497,3.519516,5.228995
2020-04-14,56.000000,39.418576,11.500000,27.500000,36.500000,48.5,44.500000,21.089744,49.166667,65.320513,87.500000,8.094886,19.357336,25.692465,34.139302,1.156412,2.765334,3.670352,4.877043
2020-04-15,60.000000,42.234189,8.000000,29.000000,38.000000,45.0,52.000000,13.333333,48.333333,63.333333,75.000000,5.631225,20.413191,26.748319,31.675641,0.804461,2.916170,3.821188,4.525092
2020-04-16,70.000000,49.273220,14.000000,36.000000,46.000000,54.0,56.000000,19.166667,51.041667,65.416667,76.875000,9.854644,25.340513,32.379545,38.010770,1.407806,3.620073,4.625649,5.430110
2020-04-17,80.000000,56.312251,20.000000,43.000000,54.000000,63.0,60.000000,25.000000,53.750000,67.500000,78.750000,14.078063,30.267835,38.010770,44.345898,2.011152,4.323976,5.430110,6.335128
2020-04-18,91.666667,64.524455,25.000000,49.666667,64.000000,73.0,66.666667,26.811594,54.094203,69.347826,79.456522,17.597579,34.960523,45.049801,51.384929,2.513940,4.994360,6.435686,7.340704
2020-04-19,103.333333,72.736658,30.000000,56.333333,74.000000,83.0,73.333333,28.623188,54.438406,71.195652,80.163043,21.117094,39.653210,52.088833,58.423961,3.016728,5.664744,7.441262,8.346280
2020-04-20,115.000000,80.948861,35.000000,63.000000,84.000000,93.0,80.000000,30.434783,54.782609,73.043478,80.869565,24.636610,44.345898,59.127864,65.462992,3.519516,6.335128,8.446838,9.351856

Santiago

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,63.500000,12.620566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,127.000000,25.241132,127.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,25.241132,NaN,NaN,NaN,1.087980,NaN,NaN,NaN
2020-03-31,141.500000,28.122994,78.000000,NaN,NaN,NaN,63.500000,59.294872,NaN,NaN,NaN,15.502428,NaN,NaN,NaN,0.668208,NaN,NaN,NaN
2020-04-01,156.000000,31.004855,29.000000,NaN,NaN,NaN,127.000000,18.589744,NaN,NaN,NaN,5.763723,NaN,NaN,NaN,0.248436,NaN,NaN,NaN
2020-04-02,164.500000,32.694223,23.000000,NaN,NaN,NaN,141.500000,14.208167,NaN,NaN,NaN,4.571229,NaN,NaN,NaN,0.197036,NaN,NaN,NaN
2020-04-03,173.000000,34.383590,17.000000,173.000000,NaN,NaN,156.000000,9.826590,100.000000,NaN,NaN,3.378734,34.383590,NaN,NaN,0.145635,1.482051,NaN,NaN
2020-04-04,193.333333,38.424821,31.666667,151.000000,NaN,NaN,161.666667,15.240518,81.908832,NaN,NaN,6.293721,30.011110,NaN,NaN,0.271281,1.293582,NaN,NaN
2020-04-05,213.666667,42.466052,46.333333,129.000000,NaN,NaN,167.333333,20.654447,63.817664,NaN,NaN,9.208707,25.638630,NaN,NaN,0.396927,1.105113,NaN,NaN
2020-04-06,234.000000,46.507283,61.000000,107.000000,NaN,NaN,173.000000,26.068376,45.726496,NaN,NaN,12.123693,21.266151,NaN,NaN,0.522573,0.916644,NaN,NaN
2020-04-07,252.500000,50.184141,49.000000,111.000000,NaN,NaN,203.500000,19.860756,44.080960,NaN,NaN,9.738705,22.061147,NaN,NaN,0.419772,0.950912,NaN,NaN
2020-04-08,271.000000,53.860999,37.000000,115.000000,271.000000,NaN,234.000000,13.653137,42.435424,100.000000,NaN,7.353716,22.856143,53.860999,NaN,0.316971,0.985179,2.321595,NaN
2020-04-09,296.000000,58.829726,43.500000,131.500000,232.500000,NaN,252.500000,14.614730,44.270672,80.218069,NaN,8.645585,26.135503,46.209160,NaN,0.372655,1.126530,1.991774,NaN
2020-04-10,321.000000,63.798453,50.000000,148.000000,194.000000,NaN,271.000000,15.576324,46.105919,60.436137,NaN,9.937454,29.414863,38.557320,NaN,0.428339,1.267882,1.661953,NaN
2020-04-11,339.000000,67.375936,51.333333,145.666667,202.333333,NaN,287.666667,15.184216,43.270613,59.757425,NaN,10.202452,28.951115,40.213563,NaN,0.439761,1.247893,1.733343,NaN
2020-04-12,357.000000,70.953419,52.666667,143.333333,210.666667,NaN,304.333333,14.792108,40.435306,59.078712,NaN,10.467451,28.487367,41.869805,NaN,0.451183,1.227904,1.804733,NaN
2020-04-13,375.000000,74.530902,54.000000,141.000000,219.000000,375.000000,321.000000,14.400000,37.600000,58.400000,100.000000,10.732450,28.023619,43.526047,74.530902,0.462606,1.207915,1.876123,3.212539
2020-04-14,389.500000,77.412764,41.500000,137.000000,225.000000,326.000000,348.000000,10.789109,35.260396,57.789109,84.282178,8.248087,27.228623,44.718541,64.792198,0.355521,1.173648,1.927523,2.792767
2020-04-15,404.000000,80.294626,29.000000,133.000000,231.000000,277.000000,375.000000,7.178218,32.920792,57.178218,68.564356,5.763723,26.433627,45.911036,55.053493,0.248436,1.139380,1.978924,2.372995
2020-04-16,433.500000,86.157723,44.000000,137.500000,230.000000,292.000000,389.500000,9.960599,31.795169,53.319131,67.435526,8.744959,27.327998,45.712287,58.034729,0.376938,1.177931,1.970357,2.501497
2020-04-17,463.000000,92.020821,59.000000,142.000000,229.000000,307.000000,404.000000,12.742981,30.669546,49.460043,66.306695,11.726195,28.222368,45.513538,61.015966,0.505439,1.216481,1.961790,2.629999
2020-04-18,475.333333,94.472060,51.666667,136.333333,229.000000,313.666667,423.666667,10.961987,28.779698,48.240029,66.004464,10.268702,27.096124,45.513538,62.340959,0.442616,1.167936,1.961790,2.687110
2020-04-19,487.666667,96.923298,44.333333,130.666667,229.000000,320.333333,443.333333,9.180994,26.889849,47.020014,65.702232,8.811209,25.969879,45.513538,63.665953,0.379793,1.119391,1.961790,2.744222
2020-04-20,500.000000,99.374537,37.000000,125.000000,229.000000,327.000000,463.000000,7.400000,25.000000,45.800000,65.400000,7.353716,24.843634,45.513538,64.990947,0.316971,1.070846,1.961790,2.801334

Providencia

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,41.000000,25.990656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,82.000000,51.981312,82.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,51.981312,NaN,NaN,NaN,3.624917,NaN,NaN,NaN
2020-03-31,84.500000,53.566108,43.500000,NaN,NaN,NaN,41.000000,52.873563,NaN,NaN,NaN,27.575452,NaN,NaN,NaN,1.922974,NaN,NaN,NaN
2020-04-01,87.000000,55.150904,5.000000,NaN,NaN,NaN,82.000000,5.747126,NaN,NaN,NaN,3.169592,NaN,NaN,NaN,0.221032,NaN,NaN,NaN
2020-04-02,90.500000,57.369619,6.000000,NaN,NaN,NaN,84.500000,6.596967,NaN,NaN,NaN,3.803511,NaN,NaN,NaN,0.265238,NaN,NaN,NaN
2020-04-03,94.000000,59.588333,7.000000,94.0,NaN,NaN,87.000000,7.446809,100.000000,NaN,NaN,4.437429,59.588333,NaN,NaN,0.309444,4.155393,NaN,NaN
2020-04-04,97.333333,61.701395,8.000000,70.0,NaN,NaN,89.333333,8.169667,73.717949,NaN,NaN,5.071348,44.374291,NaN,NaN,0.353650,3.094441,NaN,NaN
2020-04-05,100.666667,63.814456,9.000000,46.0,NaN,NaN,91.666667,8.892526,47.435897,NaN,NaN,5.705266,29.160248,NaN,NaN,0.397857,2.033490,NaN,NaN
2020-04-06,104.000000,65.927518,10.000000,22.0,NaN,NaN,94.000000,9.615385,21.153846,NaN,NaN,6.339184,13.946206,NaN,NaN,0.442063,0.972539,NaN,NaN
2020-04-07,109.500000,69.414069,10.500000,25.0,NaN,NaN,99.000000,9.590301,22.750836,NaN,NaN,6.656144,15.847961,NaN,NaN,0.464166,1.105158,NaN,NaN
2020-04-08,115.000000,72.900621,11.000000,28.0,115.000000,NaN,104.000000,9.565217,24.347826,100.000000,NaN,6.973103,17.749716,72.900621,NaN,0.486269,1.237777,5.083725,NaN
2020-04-09,122.000000,77.338050,12.500000,31.5,81.000000,NaN,109.500000,10.208965,25.739805,68.217054,NaN,7.923981,19.968431,51.347394,NaN,0.552579,1.392499,3.580711,NaN
2020-04-10,129.000000,81.775479,14.000000,35.0,47.000000,NaN,115.000000,10.852713,27.131783,36.434109,NaN,8.874858,22.187145,29.794167,NaN,0.618888,1.547221,2.077696,NaN
2020-04-11,131.333333,83.254622,11.666667,34.0,47.666667,NaN,119.666667,8.950828,25.930993,36.299210,NaN,7.395715,21.553227,30.216779,NaN,0.515740,1.503014,2.107167,NaN
2020-04-12,133.666667,84.733765,9.333333,33.0,48.333333,NaN,124.333333,7.048944,24.730202,36.164311,NaN,5.916572,20.919309,30.639391,NaN,0.412592,1.458808,2.136638,NaN
2020-04-13,136.000000,86.212908,7.000000,32.0,49.000000,136.0,129.000000,5.147059,23.529412,36.029412,100.000000,4.437429,20.285390,31.062004,86.212908,0.309444,1.414602,2.166109,6.012058
2020-04-14,141.500000,89.699459,9.000000,32.0,51.000000,100.5,132.500000,6.315026,22.649060,36.041917,72.108844,5.705266,20.285390,32.329840,63.708803,0.397857,1.414602,2.254522,4.442734
2020-04-15,147.000000,93.186011,11.000000,32.0,53.000000,65.0,136.000000,7.482993,21.768707,36.054422,44.217687,6.973103,20.285390,33.597677,41.204699,0.486269,1.414602,2.342934,2.873410
2020-04-16,155.500000,98.574317,14.000000,33.5,56.500000,71.0,141.500000,8.924423,21.555085,36.319894,45.584453,8.874858,21.236268,35.816392,45.008209,0.618888,1.480911,2.497656,3.138648
2020-04-17,164.000000,103.962624,17.000000,35.0,60.000000,77.0,147.000000,10.365854,21.341463,36.585366,46.951220,10.776613,22.187145,38.035106,48.811720,0.751507,1.547221,2.652378,3.403886
2020-04-18,169.333333,107.343523,16.666667,38.0,61.666667,80.0,152.666667,9.873532,22.375790,36.427281,47.226739,10.565307,24.088901,39.091637,50.713475,0.736772,1.679840,2.726056,3.536505
2020-04-19,174.666667,110.724421,16.333333,41.0,63.333333,83.0,158.333333,9.381210,23.410117,36.269196,47.502258,10.354001,25.990656,40.148168,52.615231,0.722036,1.812459,2.799733,3.669123
2020-04-20,180.000000,114.105319,16.000000,44.0,65.000000,86.0,164.000000,8.888889,24.444444,36.111111,47.777778,10.142695,27.892411,41.204699,54.516986,0.707301,1.945078,2.873410,3.801742

Nunoa

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,33.500000,13.389717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,67.000000,26.779433,67.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,26.779433,NaN,NaN,NaN,1.584582,NaN,NaN,NaN
2020-03-31,75.500000,30.176824,42.000000,NaN,NaN,NaN,33.500000,60.119048,NaN,NaN,NaN,16.787108,NaN,NaN,NaN,0.993320,NaN,NaN,NaN
2020-04-01,84.000000,33.574215,17.000000,NaN,NaN,NaN,67.000000,20.238095,NaN,NaN,NaN,6.794782,NaN,NaN,NaN,0.402058,NaN,NaN,NaN
2020-04-02,88.500000,35.372834,13.000000,NaN,NaN,NaN,75.500000,14.957757,NaN,NaN,NaN,5.196009,NaN,NaN,NaN,0.307456,NaN,NaN,NaN
2020-04-03,93.000000,37.171452,9.000000,93.000000,NaN,NaN,84.000000,9.677419,100.000000,NaN,NaN,3.597237,37.171452,NaN,NaN,0.212854,2.199494,NaN,NaN
2020-04-04,97.666667,39.036686,10.666667,75.333333,NaN,NaN,87.000000,10.812984,79.127726,NaN,NaN,4.263392,30.110209,NaN,NaN,0.252272,1.781669,NaN,NaN
2020-04-05,102.333333,40.901921,12.333333,57.666667,NaN,NaN,90.000000,11.948548,58.255452,NaN,NaN,4.929547,23.048965,NaN,NaN,0.291689,1.363844,NaN,NaN
2020-04-06,107.000000,42.767155,14.000000,40.000000,NaN,NaN,93.000000,13.084112,37.383178,NaN,NaN,5.595703,15.987721,NaN,NaN,0.331107,0.946019,NaN,NaN
2020-04-07,112.500000,44.965467,12.500000,37.000000,NaN,NaN,100.000000,11.203073,33.098368,NaN,NaN,4.996163,14.788642,NaN,NaN,0.295631,0.875068,NaN,NaN
2020-04-08,118.000000,47.163778,11.000000,34.000000,118.000000,NaN,107.000000,9.322034,28.813559,100.000000,NaN,4.396623,13.589563,47.163778,NaN,0.260155,0.804116,2.790756,NaN
2020-04-09,136.500000,54.558099,24.000000,48.000000,103.000000,NaN,112.500000,16.596501,34.406780,78.387097,NaN,9.592633,19.185266,41.168383,NaN,0.567611,1.135223,2.435999,NaN
2020-04-10,155.000000,61.952421,37.000000,62.000000,88.000000,NaN,118.000000,23.870968,40.000000,56.774194,NaN,14.788642,24.780968,35.172987,NaN,0.875068,1.466329,2.081242,NaN
2020-04-11,160.333333,64.084117,30.000000,62.666667,87.666667,NaN,130.333333,19.032887,39.142300,54.808527,NaN,11.990791,25.047430,35.039756,NaN,0.709514,1.482096,2.073358,NaN
2020-04-12,165.666667,66.215813,23.000000,63.333333,87.333333,NaN,142.666667,14.194806,38.284600,52.842860,NaN,9.192940,25.313892,34.906525,NaN,0.543961,1.497863,2.065475,NaN
2020-04-13,171.000000,68.347509,16.000000,64.000000,87.000000,171.000000,155.000000,9.356725,37.426901,50.877193,100.000000,6.395089,25.580354,34.773294,68.347509,0.378408,1.513630,2.057591,4.044231
2020-04-14,179.500000,71.744900,16.500000,67.000000,91.000000,146.000000,163.000000,9.199639,37.330472,50.704554,82.180851,6.594935,26.779433,36.372066,58.355183,0.390233,1.584582,2.152193,3.452969
2020-04-15,188.000000,75.142291,17.000000,70.000000,95.000000,121.000000,171.000000,9.042553,37.234043,50.531915,64.361702,6.794782,27.978513,37.970838,48.362857,0.402058,1.655533,2.246795,2.861708
2020-04-16,202.500000,80.937840,23.000000,66.000000,102.500000,127.000000,179.500000,11.203304,32.902736,50.611580,62.826012,9.192940,26.379740,40.968536,50.761016,0.543961,1.560931,2.424174,3.003610
2020-04-17,217.000000,86.733389,29.000000,62.000000,110.000000,133.000000,188.000000,13.364055,28.571429,50.691244,61.290323,11.591098,24.780968,43.966234,53.159174,0.685864,1.466329,2.601552,3.145513
2020-04-18,224.666667,89.797702,27.000000,64.333333,114.000000,137.666667,197.666667,12.103815,28.630952,50.738607,61.276882,10.791712,25.713585,45.565006,55.024408,0.638563,1.521514,2.696154,3.255882
2020-04-19,232.333333,92.862015,25.000000,66.666667,118.000000,142.333333,207.333333,10.843574,28.690476,50.785970,61.263441,9.992326,26.646202,47.163778,56.889642,0.591262,1.576698,2.790756,3.366251
2020-04-20,240.000000,95.926329,23.000000,69.000000,122.000000,147.000000,217.000000,9.583333,28.750000,50.833333,61.250000,9.192940,27.578819,48.762550,58.754876,0.543961,1.631883,2.885358,3.476620

Las Condes

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,90.500000,27.361311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,181.000000,54.722623,181.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,54.722623,NaN,NaN,NaN,0.552754,NaN,NaN,NaN
2020-03-31,194.500000,58.804144,104.000000,NaN,NaN,NaN,90.500000,56.490385,NaN,NaN,NaN,31.442833,NaN,NaN,NaN,0.317604,NaN,NaN,NaN
2020-04-01,208.000000,62.885666,27.000000,NaN,NaN,NaN,181.000000,12.980769,NaN,NaN,NaN,8.163043,NaN,NaN,NaN,0.082455,NaN,NaN,NaN
2020-04-02,216.000000,65.304345,21.500000,NaN,NaN,NaN,194.500000,10.061813,NaN,NaN,NaN,6.500201,NaN,NaN,NaN,0.065659,NaN,NaN,NaN
2020-04-03,224.000000,67.723025,16.000000,224.000000,NaN,NaN,208.000000,7.142857,100.000000,NaN,NaN,4.837359,67.723025,NaN,NaN,0.048862,0.684071,NaN,NaN
2020-04-04,235.333333,71.149487,22.000000,175.000000,NaN,NaN,213.333333,9.154670,76.614987,NaN,NaN,6.651369,52.908613,NaN,NaN,0.067186,0.534430,NaN,NaN
2020-04-05,246.666667,74.575950,28.000000,126.000000,NaN,NaN,218.666667,11.166482,53.229974,NaN,NaN,8.465378,38.094202,NaN,NaN,0.085509,0.384790,NaN,NaN
2020-04-06,258.000000,78.002413,34.000000,77.000000,NaN,NaN,224.000000,13.178295,29.844961,NaN,NaN,10.279388,23.279790,NaN,NaN,0.103832,0.235149,NaN,NaN
2020-04-07,262.000000,79.211752,21.000000,67.500000,NaN,NaN,241.000000,8.092907,25.824736,NaN,NaN,6.349034,20.407608,NaN,NaN,0.064132,0.206137,NaN,NaN
2020-04-08,266.000000,80.421092,8.000000,58.000000,266.000000,NaN,258.000000,3.007519,21.804511,100.000000,NaN,2.418679,17.535426,80.421092,NaN,0.024431,0.177126,0.812334,NaN
2020-04-09,273.500000,82.688604,11.500000,57.500000,183.000000,NaN,262.000000,4.172799,21.044604,67.793594,NaN,3.476852,17.384259,55.327293,NaN,0.035120,0.175599,0.558862,NaN
2020-04-10,281.000000,84.956116,15.000000,57.000000,100.000000,NaN,266.000000,5.338078,20.284698,35.587189,NaN,4.535024,17.233091,30.233493,NaN,0.045808,0.174072,0.305389,NaN
2020-04-11,286.000000,86.467791,15.000000,50.666667,96.000000,NaN,271.000000,5.247908,17.802411,33.634702,NaN,4.535024,15.318303,29.024154,NaN,0.045808,0.154730,0.293173,NaN
2020-04-12,291.000000,87.979465,15.000000,44.333333,92.000000,NaN,276.000000,5.157738,15.320124,31.682216,NaN,4.535024,13.403515,27.814814,NaN,0.045808,0.135389,0.280958,NaN
2020-04-13,296.000000,89.491140,15.000000,38.000000,88.000000,296.000000,281.000000,5.067568,12.837838,29.729730,100.000000,4.535024,11.488727,26.605474,89.491140,0.045808,0.116048,0.268742,0.903951
2020-04-14,301.000000,91.002815,12.500000,39.000000,85.000000,210.500000,288.500000,4.167771,12.954867,28.263558,70.424837,3.779187,11.791062,25.698469,63.641503,0.038174,0.119102,0.259580,0.642843
2020-04-15,306.000000,92.514489,10.000000,40.000000,82.000000,125.000000,296.000000,3.267974,13.071895,26.797386,40.849673,3.023349,12.093397,24.791464,37.791867,0.030539,0.122156,0.250419,0.381736
2020-04-16,313.000000,94.630834,12.000000,39.500000,72.000000,118.500000,301.000000,3.821487,12.629698,23.086193,37.924837,3.628019,11.942230,21.768115,35.826690,0.036647,0.120629,0.219880,0.361886
2020-04-17,320.000000,96.747178,14.000000,39.000000,62.000000,112.000000,306.000000,4.375000,12.187500,19.375000,35.000000,4.232689,11.791062,18.744766,33.861512,0.042754,0.119102,0.189341,0.342035
2020-04-18,322.000000,97.351848,11.333333,36.000000,61.333333,108.666667,310.666667,3.530164,11.192485,19.051636,33.762781,3.426463,10.884058,18.543209,32.853729,0.034611,0.109940,0.187305,0.331856
2020-04-19,324.000000,97.956518,8.666667,33.000000,60.666667,105.333333,315.333333,2.685327,10.197469,18.728272,32.525562,2.620236,9.977053,18.341653,31.845946,0.026467,0.100778,0.185269,0.321676
2020-04-20,326.000000,98.561188,6.000000,30.000000,60.000000,102.000000,320.000000,1.840491,9.202454,18.404908,31.288344,1.814010,9.070048,18.140096,30.838163,0.018323,0.091617,0.183233,0.311497

Vitacura

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,41.500000,42.883419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,83.000000,85.766838,83.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,85.766838,NaN,NaN,NaN,3.828877,NaN,NaN,NaN
2020-03-31,86.500000,89.383512,45.000000,NaN,NaN,NaN,41.500000,53.888889,NaN,NaN,NaN,46.500093,NaN,NaN,NaN,2.075897,NaN,NaN,NaN
2020-04-01,90.000000,93.000186,7.000000,NaN,NaN,NaN,83.000000,7.777778,NaN,NaN,NaN,7.233348,NaN,NaN,NaN,0.322917,NaN,NaN,NaN
2020-04-02,95.000000,98.166863,8.500000,NaN,NaN,NaN,86.500000,8.888889,NaN,NaN,NaN,8.783351,NaN,NaN,NaN,0.392114,NaN,NaN,NaN
2020-04-03,100.000000,103.333540,10.000000,100.0,NaN,NaN,90.000000,10.000000,100.000000,NaN,NaN,10.333354,103.333540,NaN,NaN,0.461310,4.613104,NaN,NaN
2020-04-04,104.666667,108.155772,11.333333,77.0,NaN,NaN,93.333333,10.760234,75.730994,NaN,NaN,11.711135,79.566826,NaN,NaN,0.522819,3.552090,NaN,NaN
2020-04-05,109.333333,112.978004,12.666667,54.0,NaN,NaN,96.666667,11.520468,51.461988,NaN,NaN,13.088915,55.800112,NaN,NaN,0.584327,2.491076,NaN,NaN
2020-04-06,114.000000,117.800236,14.000000,31.0,NaN,NaN,100.000000,12.280702,27.192982,NaN,NaN,14.466696,32.033397,NaN,NaN,0.645835,1.430062,NaN,NaN
2020-04-07,114.000000,117.800236,7.000000,27.5,NaN,NaN,107.000000,6.140351,24.122807,NaN,NaN,7.233348,28.416724,NaN,NaN,0.322917,1.268604,NaN,NaN
2020-04-08,114.000000,117.800236,0.000000,24.0,114.000000,NaN,114.000000,0.000000,21.052632,100.000000,NaN,0.000000,24.800050,117.800236,NaN,0.000000,1.107145,5.258939,NaN
2020-04-09,116.500000,120.383574,2.500000,21.5,75.000000,NaN,114.000000,2.100840,18.509509,65.126050,NaN,2.583339,22.216711,77.500155,NaN,0.115328,0.991817,3.459828,NaN
2020-04-10,119.000000,122.966913,5.000000,19.0,36.000000,NaN,114.000000,4.201681,15.966387,30.252101,NaN,5.166677,19.633373,37.200074,NaN,0.230655,0.876490,1.660718,NaN
2020-04-11,121.666667,125.722474,6.000000,17.0,36.333333,NaN,115.666667,4.900858,14.056331,29.879353,NaN,6.200012,17.566702,37.544520,NaN,0.276786,0.784228,1.676095,NaN
2020-04-12,124.333333,128.478035,7.000000,15.0,36.666667,NaN,117.333333,5.600035,12.146276,29.506606,NaN,7.233348,15.500031,37.888965,NaN,0.322917,0.691966,1.691472,NaN
2020-04-13,127.000000,131.233596,8.000000,13.0,37.000000,127.000000,119.000000,6.299213,10.236220,29.133858,100.000000,8.266683,13.433360,38.233410,131.233596,0.369048,0.599704,1.706849,5.858643
2020-04-14,127.500000,131.750264,4.500000,13.5,32.500000,86.000000,123.000000,3.540231,10.586860,25.504429,67.578125,4.650009,13.950028,33.583401,88.866844,0.207590,0.622769,1.499259,3.967270
2020-04-15,128.000000,132.266931,1.000000,14.0,28.000000,45.000000,127.000000,0.781250,10.937500,21.875000,35.156250,1.033335,14.466696,28.933391,46.500093,0.046131,0.645835,1.291669,2.075897
2020-04-16,129.000000,133.300267,1.500000,12.5,22.000000,42.500000,127.500000,1.159856,9.699519,17.091346,32.962740,1.550003,12.916693,22.733379,43.916755,0.069197,0.576638,1.014883,1.960569
2020-04-17,130.000000,134.333602,2.000000,11.0,16.000000,40.000000,128.000000,1.538462,8.461538,12.307692,30.769231,2.066671,11.366689,16.533366,41.333416,0.092262,0.507441,0.738097,1.845242
2020-04-18,130.666667,135.022492,2.000000,9.0,16.666667,37.333333,128.666667,1.530692,6.903652,12.750583,28.593629,2.066671,9.300019,17.222257,38.577855,0.092262,0.415179,0.768851,1.722226
2020-04-19,131.333333,135.711383,2.000000,7.0,17.333333,34.666667,129.333333,1.522922,5.345765,13.193473,26.418026,2.066671,7.233348,17.911147,35.822294,0.092262,0.322917,0.799605,1.599210
2020-04-20,132.000000,136.400273,2.000000,5.0,18.000000,32.000000,130.000000,1.515152,3.787879,13.636364,24.242424,2.066671,5.166677,18.600037,33.066733,0.092262,0.230655,0.830359,1.476193

San Bernardo

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,16.000000,4.778459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,32.000000,9.556917,32.0,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,9.556917,NaN,NaN,NaN,0.241947,NaN,NaN,NaN
2020-03-31,36.500000,10.900859,20.5,NaN,NaN,NaN,16.000000,60.975610,NaN,NaN,NaN,6.122400,NaN,NaN,NaN,0.154997,NaN,NaN,NaN
2020-04-01,41.000000,12.244800,9.0,NaN,NaN,NaN,32.000000,21.951220,NaN,NaN,NaN,2.687883,NaN,NaN,NaN,0.068048,NaN,NaN,NaN
2020-04-02,47.000000,14.036722,10.5,NaN,NaN,NaN,36.500000,22.296364,NaN,NaN,NaN,3.135864,NaN,NaN,NaN,0.079389,NaN,NaN,NaN
2020-04-03,53.000000,15.828644,12.0,53.000000,NaN,NaN,41.000000,22.641509,100.000000,NaN,NaN,3.583844,15.828644,NaN,NaN,0.090730,0.400725,NaN,NaN
2020-04-04,60.000000,17.919220,15.0,49.333333,NaN,NaN,45.000000,24.553799,85.585586,NaN,NaN,4.479805,14.733581,NaN,NaN,0.113413,0.373002,NaN,NaN
2020-04-05,67.000000,20.009796,18.0,45.666667,NaN,NaN,49.000000,26.466089,71.171171,NaN,NaN,5.375766,13.638518,NaN,NaN,0.136095,0.345279,NaN,NaN
2020-04-06,74.000000,22.100372,21.0,42.000000,NaN,NaN,53.000000,28.378378,56.756757,NaN,NaN,6.271727,12.543454,NaN,NaN,0.158778,0.317556,NaN,NaN
2020-04-07,76.500000,22.847006,13.0,40.000000,NaN,NaN,63.500000,17.353746,52.429011,NaN,NaN,3.882498,11.946147,NaN,NaN,0.098291,0.302434,NaN,NaN
2020-04-08,79.000000,23.593640,5.0,38.000000,79.000000,NaN,74.000000,6.329114,48.101266,100.000000,NaN,1.493268,11.348839,23.593640,NaN,0.037804,0.287312,0.597307,NaN
2020-04-09,98.000000,29.268060,21.5,51.000000,82.000000,NaN,76.500000,19.403873,51.401060,86.324786,NaN,6.421054,15.231337,24.489601,NaN,0.162558,0.385603,0.619990,NaN
2020-04-10,117.000000,34.942479,38.0,64.000000,85.000000,NaN,79.000000,32.478632,54.700855,72.649573,NaN,11.348839,19.113835,25.385562,NaN,0.287312,0.483895,0.642672,NaN
2020-04-11,124.666667,37.232157,33.0,64.666667,89.666667,NaN,91.666667,27.128612,52.181522,72.004477,NaN,9.855571,19.312937,26.779279,NaN,0.249508,0.488935,0.677956,NaN
2020-04-12,132.333333,39.521836,28.0,65.333333,94.333333,NaN,104.333333,21.778592,49.662190,71.359381,NaN,8.362303,19.512040,28.172996,NaN,0.211704,0.493976,0.713240,NaN
2020-04-13,140.000000,41.811514,23.0,66.000000,99.000000,140.0,117.000000,16.428571,47.142857,70.714286,100.000000,6.869034,19.711142,29.566713,41.811514,0.173900,0.499016,0.748524,1.058519
2020-04-14,148.000000,44.200743,19.5,71.500000,101.000000,132.0,128.500000,13.342491,48.250916,68.369963,89.743590,5.823747,21.353737,30.164021,39.422284,0.147437,0.540601,0.763646,0.998033
2020-04-15,156.000000,46.589972,16.0,77.000000,103.000000,124.0,140.000000,10.256410,49.358974,66.025641,79.487179,4.778459,22.996333,30.761328,37.033055,0.120974,0.582186,0.778768,0.937546
2020-04-16,177.000000,52.861699,29.0,79.000000,113.500000,140.5,148.000000,15.734266,45.134033,64.325952,79.390054,8.660956,23.593640,33.897191,41.960841,0.219265,0.597307,0.858157,1.062300
2020-04-17,198.000000,59.133427,42.0,81.000000,124.000000,157.0,156.000000,21.212121,40.909091,62.626263,79.292929,12.543454,24.190947,37.033055,46.888626,0.317556,0.612429,0.937546,1.187054
2020-04-18,211.000000,63.015924,41.0,86.333333,135.333333,166.0,170.000000,19.626646,40.915484,63.973064,78.740996,12.244800,25.783767,40.417797,49.576509,0.309995,0.652754,1.023235,1.255101
2020-04-19,224.000000,66.898422,40.0,91.666667,146.666667,175.0,184.000000,18.041171,40.921877,65.319865,78.189064,11.946147,27.376586,43.802538,52.264392,0.302434,0.693078,1.108925,1.323149
2020-04-20,237.000000,70.780920,39.0,97.000000,158.000000,184.0,198.000000,16.455696,40.928270,66.666667,77.637131,11.647493,28.969406,47.187280,54.952275,0.294873,0.733403,1.194615,1.391197

El Bosque

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,9.000000,5.232558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,18.000000,10.465116,18.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,10.465116,NaN,NaN,NaN,0.742207,NaN,NaN,NaN
2020-03-31,23.000000,13.372093,14.000000,NaN,NaN,NaN,9.000000,67.857143,NaN,NaN,NaN,8.139535,NaN,NaN,NaN,0.577272,NaN,NaN,NaN
2020-04-01,28.000000,16.279070,10.000000,NaN,NaN,NaN,18.000000,35.714286,NaN,NaN,NaN,5.813953,NaN,NaN,NaN,0.412337,NaN,NaN,NaN
2020-04-02,31.500000,18.313953,8.500000,NaN,NaN,NaN,23.000000,27.857143,NaN,NaN,NaN,4.941860,NaN,NaN,NaN,0.350487,NaN,NaN,NaN
2020-04-03,35.000000,20.348837,7.000000,35.000000,NaN,NaN,28.000000,20.000000,100.000000,NaN,NaN,4.069767,20.348837,NaN,NaN,0.288636,1.443180,NaN,NaN
2020-04-04,35.666667,20.736434,5.333333,29.666667,NaN,NaN,30.333333,15.135135,83.783784,NaN,NaN,3.100775,17.248062,NaN,NaN,0.219913,1.223267,NaN,NaN
2020-04-05,36.333333,21.124031,3.666667,24.333333,NaN,NaN,32.666667,10.270270,67.567568,NaN,NaN,2.131783,14.147287,NaN,NaN,0.151190,1.003354,NaN,NaN
2020-04-06,37.000000,21.511628,2.000000,19.000000,NaN,NaN,35.000000,5.405405,51.351351,NaN,NaN,1.162791,11.046512,NaN,NaN,0.082467,0.783441,NaN,NaN
2020-04-07,41.500000,24.127907,5.500000,18.500000,NaN,NaN,36.000000,12.485311,45.240893,NaN,NaN,3.197674,10.755814,NaN,NaN,0.226785,0.762824,NaN,NaN
2020-04-08,46.000000,26.744186,9.000000,18.000000,46.000000,NaN,37.000000,19.565217,39.130435,100.000000,NaN,5.232558,10.465116,26.744186,NaN,0.371103,0.742207,1.896751,NaN
2020-04-09,55.000000,31.976744,13.500000,23.500000,46.000000,NaN,41.500000,23.845109,42.221467,85.937500,NaN,7.848837,13.662791,26.744186,NaN,0.556655,0.968992,1.896751,NaN
2020-04-10,64.000000,37.209302,18.000000,29.000000,46.000000,NaN,46.000000,28.125000,45.312500,71.875000,NaN,10.465116,16.860465,26.744186,NaN,0.742207,1.195778,1.896751,NaN
2020-04-11,70.333333,40.891473,18.333333,34.666667,49.000000,NaN,52.000000,26.380522,48.682229,70.005020,NaN,10.658915,20.155039,28.488372,NaN,0.755951,1.429435,2.020452,NaN
2020-04-12,76.666667,44.573643,18.666667,40.333333,52.000000,NaN,58.000000,24.636044,52.051958,68.135040,NaN,10.852713,23.449612,30.232558,NaN,0.769696,1.663093,2.144153,NaN
2020-04-13,83.000000,48.255814,19.000000,46.000000,55.000000,83.000000,64.000000,22.891566,55.421687,66.265060,100.000000,11.046512,26.744186,31.976744,48.255814,0.783441,1.896751,2.267854,3.422398
2020-04-14,88.000000,51.162791,14.500000,46.500000,56.500000,79.000000,73.500000,16.822127,52.979661,64.315326,90.322581,8.430233,27.034884,32.848837,45.930233,0.597889,1.917368,2.329705,3.257463
2020-04-15,93.000000,54.069767,10.000000,47.000000,58.000000,75.000000,83.000000,10.752688,50.537634,62.365591,80.645161,5.813953,27.325581,33.720930,43.604651,0.412337,1.937984,2.391555,3.092528
2020-04-16,100.000000,58.139535,12.000000,45.000000,64.000000,77.000000,88.000000,11.918400,45.362275,63.893076,77.238468,6.976744,26.162791,37.209302,44.767442,0.494805,1.855517,2.638958,3.174996
2020-04-17,107.000000,62.209302,14.000000,43.000000,70.000000,79.000000,93.000000,13.084112,40.186916,65.420561,73.831776,8.139535,25.000000,40.697674,45.930233,0.577272,1.773050,2.886360,3.257463
2020-04-18,113.666667,66.085271,16.000000,43.333333,73.666667,83.333333,97.666667,13.972085,38.339834,64.873550,73.368165,9.302326,25.193798,42.829457,48.449612,0.659739,1.786794,3.037550,3.436143
2020-04-19,120.333333,69.961240,18.000000,43.666667,77.333333,87.666667,102.333333,14.860058,36.492751,64.326539,72.904555,10.465116,25.387597,44.961240,50.968992,0.742207,1.800539,3.188740,3.614822
2020-04-20,127.000000,73.837209,20.000000,44.000000,81.000000,92.000000,107.000000,15.748031,34.645669,63.779528,72.440945,11.627907,25.581395,47.093023,53.488372,0.824674,1.814283,3.339931,3.793502

Quinta Normal

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,10.5,7.699754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,21.0,15.399507,21.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,15.399507,NaN,NaN,NaN,1.539951,NaN,NaN,NaN
2020-03-31,23.0,16.866127,12.500000,NaN,NaN,NaN,10.500000,58.000000,NaN,NaN,NaN,9.166373,NaN,NaN,NaN,0.916637,NaN,NaN,NaN
2020-04-01,25.0,18.332747,4.000000,NaN,NaN,NaN,21.000000,16.000000,NaN,NaN,NaN,2.933239,NaN,NaN,NaN,0.293324,NaN,NaN,NaN
2020-04-02,30.0,21.999296,7.000000,NaN,NaN,NaN,23.000000,22.285714,NaN,NaN,NaN,5.133169,NaN,NaN,NaN,0.513317,NaN,NaN,NaN
2020-04-03,35.0,25.665845,10.000000,35.0,NaN,NaN,25.000000,28.571429,100.000000,NaN,NaN,7.333099,25.665845,NaN,NaN,0.733310,2.566585,NaN,NaN
2020-04-04,37.0,27.132465,8.666667,30.0,NaN,NaN,28.333333,23.925668,82.926829,NaN,NaN,6.355352,21.999296,NaN,NaN,0.635535,2.199930,NaN,NaN
2020-04-05,39.0,28.599085,7.333333,25.0,NaN,NaN,31.666667,19.279907,65.853659,NaN,NaN,5.377606,18.332747,NaN,NaN,0.537761,1.833275,NaN,NaN
2020-04-06,41.0,30.065705,6.000000,20.0,NaN,NaN,35.000000,14.634146,48.780488,NaN,NaN,4.399859,14.666197,NaN,NaN,0.439986,1.466620,NaN,NaN
2020-04-07,49.0,35.932184,11.000000,26.0,NaN,NaN,38.000000,21.352161,52.460419,NaN,NaN,8.066409,19.066057,NaN,NaN,0.806641,1.906606,NaN,NaN
2020-04-08,57.0,41.798662,16.000000,32.0,57.000000,NaN,41.000000,28.070175,56.140351,100.000000,NaN,11.732958,23.465916,41.798662,NaN,1.173296,2.346592,4.179866,NaN
2020-04-09,63.0,46.198522,14.000000,33.0,52.500000,NaN,49.000000,22.730740,52.707857,84.782609,NaN,10.266338,24.199226,38.498768,NaN,1.026634,2.419923,3.849877,NaN
2020-04-10,69.0,50.598381,12.000000,34.0,48.000000,NaN,57.000000,17.391304,49.275362,69.565217,NaN,8.799718,24.932535,35.198874,NaN,0.879972,2.493254,3.519887,NaN
2020-04-11,74.0,54.264930,13.000000,37.0,51.666667,NaN,61.000000,17.546584,49.913734,69.789510,NaN,9.533028,27.132465,37.887676,NaN,0.953303,2.713247,3.788768,NaN
2020-04-12,79.0,57.931480,14.000000,40.0,55.333333,NaN,65.000000,17.701863,50.552105,70.013803,NaN,10.266338,29.332395,40.576479,NaN,1.026634,2.933239,4.057648,NaN
2020-04-13,84.0,61.598029,15.000000,43.0,59.000000,84.000000,69.000000,17.857143,51.190476,70.238095,100.000000,10.999648,31.532324,43.265282,61.598029,1.099965,3.153232,4.326528,6.159803
2020-04-14,94.5,69.297782,18.000000,45.5,64.500000,84.000000,76.500000,18.928571,48.452381,68.452381,90.000000,13.199578,33.365599,47.298486,61.598029,1.319958,3.336560,4.729849,6.159803
2020-04-15,105.0,76.997536,21.000000,48.0,70.000000,84.000000,84.000000,20.000000,45.714286,66.666667,80.000000,15.399507,35.198874,51.331691,61.598029,1.539951,3.519887,5.133169,6.159803
2020-04-16,115.0,84.330635,20.500000,52.0,77.000000,92.000000,94.500000,18.000000,45.257143,66.933333,80.000000,15.032852,38.132113,56.464860,67.464508,1.503285,3.813211,5.646486,6.746451
2020-04-17,125.0,91.663733,20.000000,56.0,84.000000,100.000000,105.000000,16.000000,44.800000,67.200000,80.000000,14.666197,41.065353,61.598029,73.330987,1.466620,4.106535,6.159803,7.333099
2020-04-18,133.0,97.530212,21.333333,59.0,86.666667,104.666667,111.666667,16.035794,44.408054,65.381655,78.836689,15.643944,43.265282,63.553522,76.753099,1.564394,4.326528,6.355352,7.675310
2020-04-19,141.0,103.396691,22.666667,62.0,89.333333,109.333333,118.333333,16.071588,44.016107,63.563311,77.673378,16.621690,45.465212,65.509015,80.175212,1.662169,4.546521,6.550901,8.017521
2020-04-20,149.0,109.263170,24.000000,65.0,92.000000,114.000000,125.000000,16.107383,43.624161,61.744966,76.510067,17.599437,47.665141,67.464508,83.597325,1.759944,4.766514,6.746451,8.359732

Pedro Aguirre Cerda

,cum_cases,cum_cases_per_100th,new_cases,new_cases3,new_cases5,new_cases7,shift_cum_cases,increment,increment3,increment5,increment7,new_cases_per_100th,new_cases3_per_100th,new_cases5_per_100th,new_cases7_per_100th,new_cas_per_100th_area,new_cas3_per_100th_area,new_cas5_per_100th_area,new_cas7_per_100th_area
2020-03-28,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-29,3.500000,3.246663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-30,7.000000,6.493326,7.000000,NaN,NaN,NaN,0.000000,100.000000,NaN,NaN,NaN,6.493326,NaN,NaN,NaN,0.541110,NaN,NaN,NaN
2020-03-31,10.000000,9.276180,6.500000,NaN,NaN,NaN,3.500000,73.076923,NaN,NaN,NaN,6.029517,NaN,NaN,NaN,0.502460,NaN,NaN,NaN
2020-04-01,13.000000,12.059034,6.000000,NaN,NaN,NaN,7.000000,46.153846,NaN,NaN,NaN,5.565708,NaN,NaN,NaN,0.463809,NaN,NaN,NaN
2020-04-02,13.000000,12.059034,3.000000,NaN,NaN,NaN,10.000000,23.076923,NaN,NaN,NaN,2.782854,NaN,NaN,NaN,0.231904,NaN,NaN,NaN
2020-04-03,13.000000,12.059034,0.000000,13.000000,NaN,NaN,13.000000,0.000000,100.000000,NaN,NaN,0.000000,12.059034,NaN,NaN,0.000000,1.004919,NaN,NaN
2020-04-04,14.000000,12.986652,1.000000,11.666667,NaN,NaN,13.000000,6.250000,85.416667,NaN,NaN,0.927618,10.822210,NaN,NaN,0.077301,0.901851,NaN,NaN
2020-04-05,15.000000,13.914270,2.000000,10.333333,NaN,NaN,13.000000,12.500000,70.833333,NaN,NaN,1.855236,9.585386,NaN,NaN,0.154603,0.798782,NaN,NaN
2020-04-06,16.000000,14.841888,3.000000,9.000000,NaN,NaN,13.000000,18.750000,56.250000,NaN,NaN,2.782854,8.348562,NaN,NaN,0.231904,0.695713,NaN,NaN
2020-04-07,17.500000,16.233314,3.000000,7.500000,NaN,NaN,14.500000,17.269737,43.914474,NaN,NaN,2.782854,6.957135,NaN,NaN,0.231904,0.579761,NaN,NaN
2020-04-08,19.000000,17.624741,3.000000,6.000000,19.000000,NaN,16.000000,15.789474,31.578947,100.000000,NaN,2.782854,5.565708,17.624741,NaN,0.231904,0.463809,1.468728,NaN
2020-04-09,27.500000,25.509494,10.000000,14.500000,24.000000,NaN,17.500000,31.505848,47.733918,90.277778,NaN,9.276180,13.450461,22.262831,NaN,0.773015,1.120872,1.855236,NaN
2020-04-10,36.000000,33.394247,17.000000,23.000000,29.000000,NaN,19.000000,47.222222,63.888889,80.555556,NaN,15.769505,21.335213,26.900921,NaN,1.314125,1.777934,2.241743,NaN
2020-04-11,42.000000,38.959955,17.333333,28.000000,33.000000,NaN,24.666667,42.592593,66.049383,79.012346,NaN,16.078711,25.973303,30.611393,NaN,1.339893,2.164442,2.550949,NaN
2020-04-12,48.000000,44.525663,17.666667,33.000000,37.000000,NaN,30.333333,37.962963,68.209877,77.469136,NaN,16.387917,30.611393,34.321865,NaN,1.365660,2.550949,2.860155,NaN
2020-04-13,54.000000,50.091370,18.000000,38.000000,41.000000,54.000000,36.000000,33.333333,70.370370,75.925926,100.000000,16.697123,35.249483,38.032337,50.091370,1.391427,2.937457,3.169361,4.174281
2020-04-14,62.000000,57.512314,17.000000,44.500000,49.000000,58.500000,45.000000,28.095238,71.613757,78.677249,95.000000,15.769505,41.279000,45.453281,54.265651,1.314125,3.439917,3.787773,4.522138
2020-04-15,70.000000,64.933258,16.000000,51.000000,57.000000,63.000000,54.000000,22.857143,72.857143,81.428571,90.000000,14.841888,47.308516,52.874224,58.439932,1.236824,3.942376,4.406185,4.869994
2020-04-16,74.000000,68.643730,12.000000,46.500000,59.500000,64.000000,62.000000,16.556777,63.351648,80.457875,86.666667,11.131416,43.134236,55.193269,59.367550,0.927618,3.594520,4.599439,4.947296
2020-04-17,78.000000,72.354202,8.000000,42.000000,62.000000,65.000000,70.000000,10.256410,53.846154,79.487179,83.333333,7.420944,38.959955,57.512314,60.295168,0.618412,3.246663,4.792693,5.024597
2020-04-18,81.666667,75.755468,9.000000,39.666667,64.666667,68.666667,72.666667,10.957457,49.006050,79.208681,84.019975,8.348562,36.795513,59.985962,63.696434,0.695713,3.066293,4.998830,5.308036
2020-04-19,85.333333,79.156733,10.000000,37.333333,67.333333,72.333333,75.333333,11.658504,44.165946,78.930183,84.706617,9.276180,34.631071,62.459610,67.097700,0.773015,2.885923,5.204967,5.591475
2020-04-20,89.000000,82.557999,11.000000,35.000000,70.000000,76.000000,78.000000,12.359551,39.325843,78.651685,85.393258,10.203798,32.466629,64.933258,70.498966,0.850316,2.705552,5.411105,5.874914

In [91]:
lst_ts = []
lst_ts_tmp = []

for ind in range(ncmn):
    area = dict_area[lst_cmn[ind]]
    lst_ts_tmp.append(bld_df(lst_df[ind], area))

for ind in range(ncmn):
    lst_ts.append(itp_df(lst_ts_tmp[ind]))

for ind, df in enumerate(lst_ts):
    row = df[df.index == pd.to_datetime(cmn_date[ind]['Fecha'])].to_numpy()
    print(row.shape, row)

(0, 19) []
(0, 19) []
(0, 19) []
(0, 19) []
(0, 19) []
(0, 19) []
(0, 19) []
(1, 19) [[1.48000000e+02 4.42007431e+01 1.95000000e+01 7.15000000e+01
  1.01000000e+02 1.32000000e+02 1.28500000e+02 1.33424908e+01
  4.82509158e+01 6.83699634e+01 8.97435897e+01 5.82374655e+00
  2.13537374e+01 3.01640206e+01 3.94222843e+01 1.47436622e-01
  5.40600946e-01 7.63646091e-01 9.98032515e-01]]
(1, 19) [[88.         51.1627907  14.5        46.5        56.5        79.
  73.5        16.82212722 52.97966058 64.31532582 90.32258065  8.43023256
  27.03488372 32.84883721 45.93023256  0.59788883  1.91736764  2.32970477
   3.2574633 ]]
(0, 19) []
(0, 19) []